#remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g mouse on

#vim
setw -g mode-keys vi


#Split panes using | and -
bind v split-window -h
bind s split-window -v
unbind '"'
unbind %

#Reload config file
bind r source-file ~/.tmux.conf

# HJKL keybinds
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# improve colors
set -g default-terminal "screen-256color"

set-option -g status-justify centre

set -g status-bg default
set -g status-left ''
set -g status-right ''

set -g window-status-format '#[fg=black,bright,dim]#I#[fg=black,bright,nodim]:#[fg=black,bright,dim]#{window_name} '
set -g window-status-current-format '#[fg=white,nobright,dim]#I#[fg=blue,bright,nodim]:#[fg=white,nobright,dim]#{window_name} '
