#! /bin/sh

sxhkd &
polybar main &
polybar secondary &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
setxkbmap -model pc104 -layout us,se -option grp:ctrls_toggle &

if [[ $(hostname) == 'obe-laptop' ]]; then
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
elif [[ $(hostname) == 'obe-desktop' ]]; then
  bspc monitor DP-0 -d 1 2 3 4 5
  bspc monitor DP-2 -d 6 7 8 9 0
fi

bspc config border_width               2
bspc config window_gap                 10
bspc config top_padding                20
bspc config bottom_padding             0
bspc config left_padding               0
bspc config right_padding              0
bspc config single_monocle             false
bspc config click_to_focus             true
bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_by_distance          true
bspc config focus_follows_pointer      true
bspc config history_aware_focus        true
bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_side
bspc config pointer_action3            resize_corner
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true



